-- Add session tracking columns to ChatOnline
ALTER TABLE "ChatOnline"
ADD COLUMN IF NOT EXISTS "joinedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS "leftAt" TIMESTAMP NULL;
